name: Run Backend Tests on EC2

on:
  workflow_run:
    workflows: ["Deploy to EC2"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests on EC2 and Capture Results
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/cpen321-jelx/backend
            
            # Ensure MongoDB is running
            docker-compose up -d mongo

            # Ensure dependencies are installed
            echo "Installing dependencies..."
            npm install

            # Run Jest tests with coverage enabled
            echo "Running Jest tests..."
            npm test -- --ci --coverage > test-results.log 2>&1
            TEST_EXIT_CODE=$?

            # Display test results
            echo "Test Results:"
            cat test-results.log

            # Verify if coverage report exists
            if [[ -d coverage ]]; then
              echo "Coverage report generated successfully."
            else
              echo "WARNING: No coverage report found!"
            fi

            # Fail workflow if tests fail
            exit $TEST_EXIT_CODE

      - name: Copy Coverage Report from EC2 to GitHub Actions Runner
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "/home/ubuntu/cpen321-jelx/backend/coverage/*"
          target: "./coverage/"


      - name: Upload Jest Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-report
          path: coverage/
          if-no-files-found: warn
