name: Run Jest Tests on EC2

on:
  workflow_run:
    workflows: ["Deploy to EC2"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/cpen321-jelx/backend
            
            # Ensure MongoDB is running
            docker-compose up -d mongo
            
            # Optionally populate the database
            if [[ "${{ secrets.POPULATE_DB }}" == "true" ]]; then
              wget -O products_db.archive https://cpen321-jelx.s3.us-west-2.amazonaws.com/products_db.archive
              docker cp products_db.archive mongo_instance:/products_db.archive
              docker exec mongo_instance mongorestore --db products_db --archive=./products_db.archive --gzip --drop
            fi

            # Run Jest tests
            npm run test:mocked
            npm run test:unmocked
            npm run test:non-functional
            npm test
