name: Run Backend Tests on EC2

on:
  workflow_run:
    workflows: ["Deploy to EC2"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/cpen321-jelx/backend
            
            # Ensure MongoDB is running
            docker-compose up -d mongo

            # Run Jest tests
            npm test
