name: Codacy Analysis
on:
  workflow_dispatch:

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v3
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
