name: Deploy to EC2

on:
  push:
    branches: 
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy backend files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./backend"
          target: "/home/ubuntu/cpen321-jelx"

      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/cpen321-jelx/backend

            # Write secrets into .env
            cat > .env <<EOF
            PORT=${{ secrets.PROD_PORT }}
            DB_URI=${{ secrets.PROD_DB_URI }}
            EOF

            # Give .env permissions
            chmod 600 .env

            # Install npm packages
            npm ci

            # Build and run container
            docker-compose down
            docker-compose --env-file .env build
            docker-compose --env-file .env up -d

  reset-db:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Reset Database on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu

            # Download dataset
            wget -O openfoodfacts-mongodbdump.gz https://static.openfoodfacts.org/data/openfoodfacts-mongodbdump.gz

            # Move the file into the container and delete from the host
            docker cp openfoodfacts-mongodbdump.gz mongo_instance:/openfoodfacts-mongodbdump.gz && rm -f openfoodfacts-mongodbdump.gz

            # Run mongorestore inside the container
            docker exec -i mongo_instance mongorestore --gzip --archive="/openfoodfacts-mongodbdump.gz" --nsFrom=off.products --nsTo=products_db.products --drop

            # Remove the dump file inside the container after restore
            docker exec -i mongo_instance rm -f /openfoodfacts-mongodbdump.gz
